### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by cosmicnet** [OxWearables/biobankAccelerometerAnalysis#127]
Hello,

I've made some minor adjustments so that this can run on Windows. I'm happy to fork and create a pull request with these changes and accompanying documentation if you are interested.

**Comment by aidendoherty** [comment]
Dear @cosmicnet - yes, that would be great! Please do fork and create a pull request which we can then look at.
Many thanks.

**Comment by cosmicnet** [comment]
Hi Aiden,

Sorry for the delay on this. I've just submitted the pull request.

**Comment by chanshing** [comment]
Fixed in https://github.com/OxWearables/biobankAccelerometerAnalysis/releases/tag/v5.1.3
