### ISSUE TITLE
Example data columns headers and features don't match

### ISSUE THREAD

**Issue by smallsr** [OxWearables/biobankAccelerometerAnalysis#173]
When running through the example classification exercise in the Usage instructions, a key error is created due to unmatched feature names between activityModels/labelled-acc-epochs.csv and activityModels/features.txt. Specifically, the features "vmfft1-14" are named in the csv as "mfft1-14". Additionally the feature "totalPower" is named in the csv as "total"

**Comment by aidendoherty** [comment]
Thanks for spotting this @smallsr 
When you get a chance, would you mind creating a pull request to suggest the fix to this?

**Comment by chanshing** [comment]
I think this may have been fixed already. Closing for now but feel free to re-open if it's indeed not fixed yet.
