### ISSUE TITLE
Refactor plotting

### ISSUE THREAD

**Issue by angerhang** [OxWearables/biobankAccelerometerAnalysis#181]
At the moment, the plotting script is a big script clotting together which makes it more cumbersome than ideal to make changes or add features. We need to refactor this badly.

https://github.com/activityMonitoring/biobankAccelerometerAnalysis/blob/master/accelerometer/accPlot.py

**Comment by chanshing** [comment]
I agree (y)

**Comment by chanshing** [comment]
@angerhang Would you like to look at `accPlot` again and have a go?

**Comment by R-Walmsley** [comment]
I know @gmertes is also using this function so cc'ing in case you've already made any changes to your own version.

**Comment by gmertes** [comment]
My changes are already merged. My only request is to keep the interface to [plotTimeSeries](https://github.com/OxWearables/biobankAccelerometerAnalysis/blob/446295152d4750f4ae7daae6a5db83740bae9a3d/accelerometer/accPlot.py#L92) the same (or at least backwards compatible).

**Comment by chanshing** [comment]
Re-open if still unfixed.
