### ISSUE TITLE
Axitivity timezone stays `Europe/London` despite user input 

### ISSUE THREAD

**Issue by angerhang** [OxWearables/biobankAccelerometerAnalysis#199]
``accProcess sampleFile --timeZone 'America/New_York`` and ``accProcess sampleFile`` produce the same timestamp in epoch and time-series files with tz being `Europe/London`. Only UNIX time in `npy` files are changed.

This is likely to be wrong. 

Not sure about what the behaviour for GeneActive. But it looks like BBAA fails for timeZone flag in general. This is a critical bug for non-UTC data.

Test cases:

```
accProcess data/sample.cwa.gz --timeZone 'America/New_York`
accProcess data/sample.cwa.gz
```
There should be at least 4/5 hours of difference between all the output time series. BTW I remember we wanted to have a much smaller sample test file for debugging purpose right? The current `sample.cwa.gz` takes too long :(

**Comment by angerhang** [comment]
I am not particularly familiar with the Axitivity reader. @chanshing would you mind working on this issue when you have the time? I will work on the GT3X time zone ticket instead.

**Comment by chanshing** [comment]
> `accProcess sampleFile --timeZone 'America/New_York` and `accProcess sampleFile` produce the same timestamp in epoch and time-series files with tz being `Europe/London`. Only UNIX time in `npy` files are changed.

Hang, I am not able to reproduce this.

TimeSeries file:
![image](https://user-images.githubusercontent.com/5551642/174550765-94eab075-9e9b-458f-96d3-d6ac36383634.png)

Epoch file:
![image](https://user-images.githubusercontent.com/5551642/174550928-68befdb8-c65f-4a18-b984-6e5a46215d3f.png)

Are you sure you checked the right output files?

**Comment by chanshing** [comment]
> This seems wrong:
> 
> https://github.com/OxWearables/biobankAccelerometerAnalysis/blob/0b8db7353c49c543de0d52369a299e79049da334/accelerometer/java/DeviceReader.java#L191
> 
> When a user supplies a time zone such as `America/New_York`, the adjusted time should observe DST directly without we having to correct it manually. A manual update is only required if we have a time zone like `EST` https://stackoverflow.com/questions/10545960/how-to-tackle-daylight-savings-using-timezone-in-java

This is correct for Axivity, but maybe not for the other devices (when I first implemented this for Axivity, I wanted to put this piece of code inside AxivityParser and not DeviceReader, because I'm aware that other devices may do things differently).
