### ISSUE TITLE
Clarification on Imputed Values and Column Naming for Reproducing Paper Features

### ISSUE THREAD

**Issue by mariascedasticity** [OxWearables/biobankAccelerometerAnalysis#250]
Hello,

I am currently working on reproducing the results of a specific paper and aim to match the features outlined in their study using the accProcess tool. However, I've encountered a couple of issues that I hope you can help clarify:

**Imputed Values:**
According to the documentation, the flag --timeSeriesDateColumn True is supposed to generate imputed values for the dataset. However, I am unsure if I am correctly interpreting its usage or if there's an additional step required to obtain these imputed values. Could you provide more detailed guidance or examples on how to use this flag effectively for imputation?

**Column Naming - MVPA vs. Moderate-Vigorous:**
In the outputs mentioned in the paper, there's a column named MVPA. In my outputs using the latest version of accProcess, this column appears as moderate-vigorous. Is this a recent change in the package's naming convention? If so, could you confirm that these columns are indeed equivalent, and this renaming is the only difference? Could it be that I'm not using a specific flag to achieve identical features?

**MET column**
In the outputs of accProcess, I got MET variable. I see no information about this in the documentation. Can you please clarify what it is? Is it Metabolic Equivalent of Task?

**Comment by chanshing** [comment]
Hi @mariascedasticity 
 
1. The --timeSeriesDateColumn option is deprecated: We now output the timeSeries.csv.gz file always. You can ignore this flag - sorry for the confusion!
1. Yes, -moderate-vigorous is MVPA in the output file. I believe it was renamed to MVPA in the paper for convenience.
1. Correct, MET is the metabolic equivalent of task. While we output this, please note that it hasn't been validated, so consider it as experimental feature.

I hope this helps and sorry for the confusion! We will fix the documentation soon.
