### ISSUE TITLE
any plan enable processing data that read into memory through other ways?

### ISSUE THREAD

**Issue by tbonewmy** [OxWearables/biobankAccelerometerAnalysis#259]
Dear developers,
From what I can know so far, the only way to process a file is giving the directory of the file to the function. The file will then be loaded and process in java code. The input and processing seems to be exclusive to Java and the python codes seems to only wrap around it to make access easy. If I have a pandas dataframe, can I somehow pass it as an input to the processing steps?

**Comment by chanshing** [comment]
Hi @tbonewmy
This package is tailored to end users wanting to simply process a file via the CLI.
I believe what you're looking for instead is something like an SDK (software development kit)? In that case, you could have a look at https://github.com/OxWearables/actipy
