### ISSUE TITLE
Minimal non wear time window

### ISSUE THREAD

**Issue by ghammad** [OxWearables/biobankAccelerometerAnalysis#261]
Hello,

while processing AX3.cwa data through `accelerometer`, we visually found some segments of NaNs that actually might be just plain rest. 
See example here:
![Actimetry-NonWear-Example](https://github.com/user-attachments/assets/d5078606-90ae-4cc5-9d85-bcf5eb22f00d)

There is little chance that our participant woke up in the middle of the night, remove the actigraph for an hour or so and then quietly attached it again.

Therefore, I'd like to be able to modify the minimal non-wear time window. Unfortunately, if I read the code correctly, the `minNonWearDuration` parameter of the `getActivitySummary` function used by the [accProcess](https://github.com/OxWearables/biobankAccelerometerAnalysis/blob/38f5a9719068e6faf87dbed1a44ccfe5e7c83361/src/accelerometer/accProcess.py#L324) function is not accessible.

Is there a way out, besides keeping the `epoch.csv.gz` file?

More generally, is there a way to avoid the replacement of the actual acceleration values by NaNs for these nonwear periods? Ideally, flagging them with optional replacement would be a nice feature.

Thanks again for the hard work you put in the package.

Greg

**Comment by chanshing** [comment]
Hi @ghammad 
We just added the option `--minNonWearDuration` that you can use to set a minimum duration that a stationary period must have to be classified as non-wear (default is 60 minutes - we will probably change this default to 90 minutes). You can also adjust the standard deviation threshold with `--stationaryStd` (default is 13 mg)

https://github.com/OxWearables/biobankAccelerometerAnalysis/blob/ba14445dd6c645f16cb3e45581044d65088eaf1f/src/accelerometer/accProcess.py#L137-L144
