### ISSUE TITLE
Does nonWearFile do anything?

### ISSUE THREAD

**Issue by muschellij2** [OxWearables/biobankAccelerometerAnalysis#268]
I'm confused as the `nonWearFile` argument does not seem to go anywhere or relate to any output file.
`accProcess` calls it 
https://github.com/OxWearables/biobankAccelerometerAnalysis/blob/b362508b2ec8be7c7150b79aae449a6391b138d2/src/accelerometer/accProcess.py#L329
but is only referenced in that file at
https://github.com/OxWearables/biobankAccelerometerAnalysis/blob/b362508b2ec8be7c7150b79aae449a6391b138d2/src/accelerometer/summarisation.py#L34

and the `resolveNonWear` function indicates
> Write .csv.gz non wear episodes file to <nonWearFile>
https://github.com/OxWearables/biobankAccelerometerAnalysis/blob/b362508b2ec8be7c7150b79aae449a6391b138d2/src/accelerometer/summarisation.py#L180

but it seems as though no csv.gz is written and only passed to `summary`:
https://github.com/OxWearables/biobankAccelerometerAnalysis/blob/b362508b2ec8be7c7150b79aae449a6391b138d2/src/accelerometer/summarisation.py#L212

**Comment by chanshing** [comment]
Hi @muschellij2 you're probably correct - it is doing nothing. I think we deprecated this bit a while ago but there's still some leftover code. We'll clean up soon. Thanks for spotting it!
